---
title: "First Knit"
author: "Jennifer Espinoza"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to high school at Palmdale High school and i graduated with the class of 2023. English is easier for me than math i find math harder than english. I would say i do best in English.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I own my own computer that i can bring to class and use at hom. I have an apple MacBook. I would rate myself a 7. I have internet connection at home it works well.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name is Jennifer Espinoza and i perfer to be called Jennifer by my classmates and instructor. My friends and family call me Jenny.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I am going to work at a hospital working as a Registered Nurse at the emergency room. My favorite subject in college is psychology. I want to achieve a degree in nursing.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have never traveled to foregine countries but in the future i would like to visit all of them. I have never been in the military.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I already took math 115 i took it last semester and didnt pass the class and that is why im taking it this summer.. I need to attain a good grade because it is a prerequisite i need to take in order to get accepted into the nursing program here at AVC.
   
 






  




